    mySql:
        driverName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mariadb
        userName: root
        password: admin
    oracle:
        driverName: com.mysql.jdbc.Driver
        url: jdbc:oracle:thin:@localhost:1521:xe
        userName: admin
        password: Password#123 